// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupExperimentPrefs.browser.search.param.google_channel_row", "trow5");
user_pref("app.normandy.startupExperimentPrefs.browser.search.param.google_channel_us", "tus5");
user_pref("app.normandy.startupExperimentPrefs.network.cookie.cookieBehavior", 5);
user_pref("app.normandy.startupExperimentPrefs.privacy.restrict3rdpartystorage.skip_list", "https://jalopnik.com,https://kinja.com;https://we.hamropatro.com,https://hamropatro.firebaseapp.com;https://stackblitz.com,*;*,https://www.blogger.com;*,https://scroll.com;https://www.messenger.com,https://www.facebook.com;https://knowyourmeme.com,https://trends.google.com");
user_pref("app.normandy.startupRolloutPrefs.fission.experiment.enrollmentStatus", 4);
user_pref("app.normandy.startupRolloutPrefs.media.peerconnection.mtransport_process", true);
user_pref("app.normandy.startupRolloutPrefs.network.process.enabled", true);
user_pref("app.normandy.user_id", "90656039-d156-4a61-9b37-6816c05d9224");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1639873494);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1639873471);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1639874070);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1639873903);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1639873524);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{8e2c7e29-658e-4503-b186-4c97f8f77215}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1639873464);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 120);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"114235\":1639873470396,\"114292\":1639873470400,\"114296\":1639873470401}");
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{2f9afaad-5477-4a7e-a413-f9dc851eb652}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1639873467);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1639873512027");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1639875319027");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1639873471092");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1639895071092");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20211216131657");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1639874070");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20211216131657");
user_pref("browser.startup.homepage_override.mstone", "95.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1639874069);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"addon_darkreader_org-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"addon_darkreader_org-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 1);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1639873468744");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "95.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "IN");
user_pref("dom.push.userAgentID", "8e3ca8066dd9411c946fd41288612cb2");
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20211216131657");
user_pref("extensions.lastAppVersion", "95.0.1");
user_pref("extensions.lastPlatformVersion", "95.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"0430f01a-dde4-4656-b4ea-f01ec9dee348\",\"formautofill@mozilla.org\":\"9a427256-e64d-42fc-b5d7-82396e81c946\",\"pictureinpicture@mozilla.org\":\"b2063507-6ec0-4a22-a088-46472fbbeb12\",\"proxy-failover@mozilla.com\":\"27b9b3c3-dd0f-4104-8e53-5e849fe04674\",\"screenshots@mozilla.org\":\"cdb53208-b1fe-429f-86f9-c13326af7299\",\"webcompat-reporter@mozilla.org\":\"744c97c9-6bd9-4a7f-937a-13fc6a14e556\",\"webcompat@mozilla.org\":\"b2dd77d7-a935-4182-9e42-00b0e03dfd4f\",\"default-theme@mozilla.org\":\"4100b874-251c-48e1-8f65-00f3511b6852\",\"addons-search-detection@mozilla.com\":\"f19cec58-7ef0-4fa9-8a14-1d7dd81b9509\",\"google@search.mozilla.org\":\"3dbcd632-4db6-4d5e-acf8-63e7e216c4ff\",\"wikipedia@search.mozilla.org\":\"57c22c0f-6000-4fe1-9904-cfbc342209bd\",\"bing@search.mozilla.org\":\"f627b344-6fe2-43e0-a192-d6b4ef1a8a30\",\"ddg@search.mozilla.org\":\"06880da9-b9d6-4a02-87cf-7924a8bb8cb9\",\"addon@darkreader.org\":\"32136b47-d7c7-408e-ba13-d7c142df326c\",\"firefox-compact-dark@mozilla.org\":\"8b0c9578-1e85-4824-b6f9-4cb83cf83b93\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1639873469);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("fission.experiment.startupEnrollmentStatus", 4);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "987dc42e-fda1-4c9e-bb05-3d20db6fca5f");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1639874063);
user_pref("toolkit.telemetry.cachedClientID", "83d2b2b4-f47d-4d55-b1cf-14f0f4ad546a");
user_pref("toolkit.telemetry.previousBuildID", "20211216131657");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
