// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.media.peerconnection.mtransport_process", true);
user_pref("app.normandy.startupRolloutPrefs.network.process.enabled", true);
user_pref("app.normandy.user_id", "68e38841-bf92-4fb8-b16c-f6ede9d813f4");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1633033985);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1633033979);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1633034232);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1633034013);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{83f37667-5e99-4d3f-9160-4cb3936f15fd}");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1633033955);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 117);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"106641\":1633033996558,\"106693\":1633033996557,\"106697\":1633033996559}");
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{89dcd399-dd8e-4072-8416-3469ef584ca0}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1633033966);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1633034018785");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1633035842785");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1633033978887");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1633055578887");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210923165649");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1633034234");
user_pref("browser.startup.homepage_override.buildID", "20210923165649");
user_pref("browser.startup.homepage_override.mstone", "92.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1633034233);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"addon_darkreader_org-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"addon_darkreader_org-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1633033972277");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "92.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "IN");
user_pref("dom.push.userAgentID", "ede2f6d99fce4af39ae639e6b3f1d9c2");
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210923165649");
user_pref("extensions.lastAppVersion", "92.0.1");
user_pref("extensions.lastPlatformVersion", "92.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"4d4103cc-0bfa-4519-b016-c8b12f02a010\",\"formautofill@mozilla.org\":\"18b9e8d4-e761-41d6-9b27-69d7c219a5d7\",\"pictureinpicture@mozilla.org\":\"8d421864-0856-4b4a-8a7e-c90f7043d3e4\",\"screenshots@mozilla.org\":\"e7fc84a1-2c02-4e96-aac5-e0183b97b33b\",\"webcompat-reporter@mozilla.org\":\"a4197f04-79f3-4e8e-b1cd-19e406ced9ac\",\"webcompat@mozilla.org\":\"c34abae9-5959-42b2-8208-7c51eff441d8\",\"default-theme@mozilla.org\":\"92df112f-50bd-44d6-97e4-988c30c68ad1\",\"google@search.mozilla.org\":\"b0a80b96-c933-4063-8002-31efe9b9d876\",\"wikipedia@search.mozilla.org\":\"12660538-3c5d-49ea-9fa1-224eef415031\",\"bing@search.mozilla.org\":\"70732c9e-855f-46af-84d4-b8a8f0c6eba6\",\"ddg@search.mozilla.org\":\"ac3e0c3b-60f6-48c6-8eea-428281af09b6\",\"addon@darkreader.org\":\"3187e685-b88b-4829-a870-1fcfe387e8ed\",\"firefox-compact-dark@mozilla.org\":\"b6c7b1db-c2f1-4716-ad6b-6fd9b48162cf\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1633033973);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgradeDialog-defaultEnabled\",\"enabled\":true,\"targeting\":\"true\",\"variables\":null,\"description\":\"Turn on upgradeDialog by default for all users\"}");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "b1deeae8-c122-482b-93d4-afe1ba4433e6");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1633034224);
user_pref("toolkit.telemetry.cachedClientID", "37a648aa-a6ed-412b-adb4-9f742c6453bd");
user_pref("toolkit.telemetry.previousBuildID", "20210923165649");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
